### ISSUE TITLE
FMOD vs AudioEngine

### ISSUE THREAD

**Issue by johnspeny** [DelinWorks/Rebound#8]
I see you are using FMod to handle audio, what benefits does it have over the inbuilt or default audio engine in axmol?. Personally I have never used FMod, just want to know what is it better at

**Comment by johnspeny** [comment]
Well I wanted to hear it from @DelinWorks because his actually using it in this project. I am only asking on a project level on things I am seeing being used.

**Comment by aismann** [comment]
> 

Yes. But this can be interesst also others later

**Comment by aismann** [comment]
yes

**Comment by DelinWorks** [comment]
@johnspeny I used FMOD because OpenAL support is not that great to be honest, first it doesn't have audio panning and sometimes the audio effect work on windows but not android and it's pretty buggy, it also doesn't support nested audio group channels, I've seen games use it and i decided to use FMOD because it might be a good choice over OpenAL, OpenAL might cause a lot of frustrations over the long run. Hope that helps!

**Comment by johnspeny** [comment]
Alright made some research, it industry standard especially because of adaptive audio(one of its features).  Let me try intergrate it n play around with its features.

**Comment by johnspeny** [comment]
I got fmod to run well on my end especially for win32
